FROM ubuntu:14.04
MAINTAINER Michael Smith <michael.smith@puppetlabs.com>
RUN apt-get -qq update
RUN apt-get -qqy install build-essential cmake libboost-all-dev liblog4cxx10-dev libssl-dev libyaml-cpp-dev

