# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/solaris10u9_64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://int-resources.ops.puppetlabs.net/vagrant/solaris10u9_64.box"

  # Provision the VM as root
  config.vm.provision :shell, path: "bootstrap.sh"
  # Setup the user environment
  config.vm.provision :shell, path: "usersetup.sh", privileged: false
end
